### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Polygrant** [kbase/narrative_method_specs#357]
When doing a search on the "protein families" tab within the results, would it be possible to rename the tab that appears?  It is nice that it names it with the exact kbase reference for the gene, but being able to customize this name would be helpful.  GREAT TOOL, thank you!

**Comment by msneddon** [comment]
Sorry- this comment must have fallen through the cracks.  I don't think anyone ever saw this issue (we don't really manage issues with github at a project level), and the code for the protein families viewers/apps aren't actually in this repo.  If you'd still like to follow up on this suggestion or have others, please report here: https://kbase.us/contact-us/  Thanks!
