### ISSUE TITLE
allow empty string to be the default of a dropdown menu

### ISSUE THREAD

**Issue by levinas** [kbase/narrative_method_specs#82]
The assembly method has a field that has a default value of "". Right now it's always set to "velvet" in the narrative interface. 

https://github.com/kbase/narrative_method_specs/blob/dev/methods/assemble_contigset_from_reads/spec.json#L108

Here are two requests:

1. Set the default to "". 
2. If the user does not select an assembler, the narrative should not send the parameter to NJS.

**Comment by msneddon** [comment]
fixed in the narrative
